/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ValuationRouteImport } from './routes/valuation'
import { Route as MapRouteImport } from './routes/map'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as Dashboard_layoutRouteImport } from './routes/dashboard/__layout'
import { Route as Dashboard_layoutSmartBuyerInsightsRouteImport } from './routes/dashboard/__layout.smart-buyer-insights'
import { Route as Dashboard_layoutKpisRouteImport } from './routes/dashboard/__layout.kpis'
import { Route as Dashboard_layoutGeographyAndDistributionRouteImport } from './routes/dashboard/__layout.geography-and-distribution'

const ValuationRoute = ValuationRouteImport.update({
  id: '/valuation',
  path: '/valuation',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const Dashboard_layoutRoute = Dashboard_layoutRouteImport.update({
  id: '/dashboard/__layout',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const Dashboard_layoutSmartBuyerInsightsRoute =
  Dashboard_layoutSmartBuyerInsightsRouteImport.update({
    id: '/smart-buyer-insights',
    path: '/smart-buyer-insights',
    getParentRoute: () => Dashboard_layoutRoute,
  } as any)
const Dashboard_layoutKpisRoute = Dashboard_layoutKpisRouteImport.update({
  id: '/kpis',
  path: '/kpis',
  getParentRoute: () => Dashboard_layoutRoute,
} as any)
const Dashboard_layoutGeographyAndDistributionRoute =
  Dashboard_layoutGeographyAndDistributionRouteImport.update({
    id: '/geography-and-distribution',
    path: '/geography-and-distribution',
    getParentRoute: () => Dashboard_layoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/map': typeof MapRoute
  '/valuation': typeof ValuationRoute
  '/dashboard': typeof Dashboard_layoutRouteWithChildren
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/geography-and-distribution': typeof Dashboard_layoutGeographyAndDistributionRoute
  '/dashboard/kpis': typeof Dashboard_layoutKpisRoute
  '/dashboard/smart-buyer-insights': typeof Dashboard_layoutSmartBuyerInsightsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/map': typeof MapRoute
  '/valuation': typeof ValuationRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/geography-and-distribution': typeof Dashboard_layoutGeographyAndDistributionRoute
  '/dashboard/kpis': typeof Dashboard_layoutKpisRoute
  '/dashboard/smart-buyer-insights': typeof Dashboard_layoutSmartBuyerInsightsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/map': typeof MapRoute
  '/valuation': typeof ValuationRoute
  '/dashboard/__layout': typeof Dashboard_layoutRouteWithChildren
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/__layout/geography-and-distribution': typeof Dashboard_layoutGeographyAndDistributionRoute
  '/dashboard/__layout/kpis': typeof Dashboard_layoutKpisRoute
  '/dashboard/__layout/smart-buyer-insights': typeof Dashboard_layoutSmartBuyerInsightsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/map'
    | '/valuation'
    | '/dashboard'
    | '/dashboard/'
    | '/dashboard/geography-and-distribution'
    | '/dashboard/kpis'
    | '/dashboard/smart-buyer-insights'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/map'
    | '/valuation'
    | '/dashboard'
    | '/dashboard/geography-and-distribution'
    | '/dashboard/kpis'
    | '/dashboard/smart-buyer-insights'
  id:
    | '__root__'
    | '/'
    | '/map'
    | '/valuation'
    | '/dashboard/__layout'
    | '/dashboard/'
    | '/dashboard/__layout/geography-and-distribution'
    | '/dashboard/__layout/kpis'
    | '/dashboard/__layout/smart-buyer-insights'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MapRoute: typeof MapRoute
  ValuationRoute: typeof ValuationRoute
  Dashboard_layoutRoute: typeof Dashboard_layoutRouteWithChildren
  DashboardIndexRoute: typeof DashboardIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/valuation': {
      id: '/valuation'
      path: '/valuation'
      fullPath: '/valuation'
      preLoaderRoute: typeof ValuationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/__layout': {
      id: '/dashboard/__layout'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof Dashboard_layoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/__layout/smart-buyer-insights': {
      id: '/dashboard/__layout/smart-buyer-insights'
      path: '/smart-buyer-insights'
      fullPath: '/dashboard/smart-buyer-insights'
      preLoaderRoute: typeof Dashboard_layoutSmartBuyerInsightsRouteImport
      parentRoute: typeof Dashboard_layoutRoute
    }
    '/dashboard/__layout/kpis': {
      id: '/dashboard/__layout/kpis'
      path: '/kpis'
      fullPath: '/dashboard/kpis'
      preLoaderRoute: typeof Dashboard_layoutKpisRouteImport
      parentRoute: typeof Dashboard_layoutRoute
    }
    '/dashboard/__layout/geography-and-distribution': {
      id: '/dashboard/__layout/geography-and-distribution'
      path: '/geography-and-distribution'
      fullPath: '/dashboard/geography-and-distribution'
      preLoaderRoute: typeof Dashboard_layoutGeographyAndDistributionRouteImport
      parentRoute: typeof Dashboard_layoutRoute
    }
  }
}

interface Dashboard_layoutRouteChildren {
  Dashboard_layoutGeographyAndDistributionRoute: typeof Dashboard_layoutGeographyAndDistributionRoute
  Dashboard_layoutKpisRoute: typeof Dashboard_layoutKpisRoute
  Dashboard_layoutSmartBuyerInsightsRoute: typeof Dashboard_layoutSmartBuyerInsightsRoute
}

const Dashboard_layoutRouteChildren: Dashboard_layoutRouteChildren = {
  Dashboard_layoutGeographyAndDistributionRoute:
    Dashboard_layoutGeographyAndDistributionRoute,
  Dashboard_layoutKpisRoute: Dashboard_layoutKpisRoute,
  Dashboard_layoutSmartBuyerInsightsRoute:
    Dashboard_layoutSmartBuyerInsightsRoute,
}

const Dashboard_layoutRouteWithChildren =
  Dashboard_layoutRoute._addFileChildren(Dashboard_layoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MapRoute: MapRoute,
  ValuationRoute: ValuationRoute,
  Dashboard_layoutRoute: Dashboard_layoutRouteWithChildren,
  DashboardIndexRoute: DashboardIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
